/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/F150.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function F150(props) {
  const { nodes, materials } = useGLTF('models/F150.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }



  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.chrome_22.geometry} material={materials.chrome} />
      <mesh geometry={nodes.plate_02.geometry} material={materials.plate} />
      <mesh geometry={nodes.chrome_26.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_25.geometry} material={materials.chrome} />
      <mesh geometry={nodes.silver_09.geometry} material={materials.silver} />
      <mesh geometry={nodes.body_11.geometry} material={materials.body} />
      <mesh geometry={nodes.glass_15.geometry} material={materials.glass} />
      <mesh geometry={nodes.chrome_23.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_95.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.brakes1_03.geometry} material={materials.brakes1} />
      <mesh geometry={nodes.brakes1_04.geometry} material={materials.brakes1} />
      <mesh geometry={nodes.black_matt_68.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_67.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_66.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_64.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_27.geometry} material={materials.interior} />
      <mesh geometry={nodes.chrome_18.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_04.geometry} material={materials.black} />
      <mesh geometry={nodes.glass_08.geometry} material={materials.glass} />
      <mesh geometry={nodes.black_06.geometry} material={materials.black} />
      <mesh geometry={nodes.black_07.geometry} material={materials.black} />
      <mesh geometry={nodes.black_matt_83.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_84.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_81.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_82.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_79.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_06.geometry} material={materials.silver} />
      <mesh geometry={nodes.chrome_19.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_75.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_72.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_56.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_01.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_16.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_06.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_02.geometry} material={materials.interior} />
      <mesh geometry={nodes.black_shiny_08.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_matt_99.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_45.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_46.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_d_02.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.black_matt_44.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_43.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_42.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_40.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_41.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_39.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.brakes1_01.geometry} material={materials.brakes1} />
      <mesh geometry={nodes.silver_05.geometry} material={materials.silver} />
      <mesh geometry={nodes.black_matt_34.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_33.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.brakes1_02.geometry} material={materials.brakes1} />
      <mesh geometry={nodes.black_matt_36.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.o_glass_b_01.geometry} material={materials.o_glass_b} />
      <mesh geometry={nodes.black_02.geometry} material={materials.black} />
      <mesh geometry={nodes.chrome_05.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_01.geometry} material={materials.black} />
      <mesh geometry={nodes.raptor_logo_01.geometry} material={materials.raptor_logo} />
      <mesh geometry={nodes.raptor_logo_02.geometry} material={materials.raptor_logo} />
      <mesh geometry={nodes.o_glass_b_03.geometry} material={materials.o_glass_b} />
      <mesh geometry={nodes.plate_01.geometry} material={materials.plate} />
      <mesh geometry={nodes.tire_03.geometry} material={materials.tire} />
      <mesh geometry={nodes.tire_02.geometry} material={materials.tire} />
      <mesh geometry={nodes.black_matt_01.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_92_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_91_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_90_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_89_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_106_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.glass_16_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.d_red_01_pivot.geometry} material={materials.d_red} />
      <mesh geometry={nodes.glass_bump_03_pivot.geometry} material={materials.glass_bump} />
      <mesh geometry={nodes.black_matt_105_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_104_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_103_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.r_lights_01_pivot.geometry} material={materials.r_lights} />
      <mesh geometry={nodes.red_bump_01_pivot.geometry} material={materials.red_bump} />
      <mesh geometry={nodes.red_01_pivot.geometry} material={materials.red} />
      <mesh geometry={nodes.black_matt_102_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_101_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_100_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.o_glass_10_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.o_glass_b_04_pivot.geometry} material={materials.o_glass_b} />
      <mesh geometry={nodes.o_glass_09_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.d_glass_05_pivot.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.black_matt_98_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_08_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.black_matt_97_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_96_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.body_10_pivot.geometry} material={materials.body} />
      <mesh geometry={nodes.chrome_24_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.glass_14_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.black_matt_94_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.glass_90_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_bump_02_pivot.geometry} material={materials.glass_bump} />
      <mesh geometry={nodes.black_matt_93_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_71_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_69_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.body_08_pivot.geometry} material={materials.body} />
      <mesh geometry={nodes.black_matt_65_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_28_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.d_glass_04_pivot.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.black_05_pivot.geometry} material={materials.black} />
      <mesh geometry={nodes.glass_12_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_bump_01_pivot.geometry} material={materials.glass_bump} />
      <mesh geometry={nodes.interior_26_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.chrome_17_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.glass_11_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_10_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_09_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.chrome_16_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_15_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_14_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_13_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_63_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_62_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_25_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_24_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.black_matt_61_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.body_07_pivot.geometry} material={materials.body} />
      <mesh geometry={nodes.black_matt_88_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.chrome_21_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.silver_d_05_pivot.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.black_matt_87_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_86_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_85_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_d_03_pivot.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.silver_d_04_pivot.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.black_matt_80_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_78_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.tire_bump_04_pivot.geometry} material={materials.tire_bump} />
      <mesh geometry={nodes.black_matt_76_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_77_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_07_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.black_matt_74_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.chrome_20_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_73_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.tire_bump_03_pivot.geometry} material={materials.tire_bump} />
      <mesh geometry={nodes.black_matt_70_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_60_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_shiny_09_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_matt_59_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_58_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_57_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_23_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.d_glass_03_pivot.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.black_matt_55_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_22_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.black_matt_54_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_53_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_21_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_20_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_07_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_19_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_18_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_17_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_15_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.glass_07_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.chrome_12_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.interior_14_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_13_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_12_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.chrome_11_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_52_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_11_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_10_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_09_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.body_06_pivot.geometry} material={materials.body} />
      <mesh geometry={nodes.black_matt_51_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_50_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.interior_08_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.d_glass_02_pivot.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.interior_05_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.black_03_pivot.geometry} material={materials.black} />
      <mesh geometry={nodes.interior_04_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.interior_03_pivot.geometry} material={materials.interior} />
      <mesh geometry={nodes.black_matt_49_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_48_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_47_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_d_01_pivot.geometry} material={materials.silver_d} />
      <mesh geometry={nodes.tire_bump_02_pivot.geometry} material={materials.tire_bump} />
      <mesh geometry={nodes.black_matt_38_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_04_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.chrome_10_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_shiny_03_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_matt_35_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_37_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.tire_bump_01_pivot.geometry} material={materials.tire_bump} />
      <mesh geometry={nodes.black_matt_32_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_31_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_29_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.o_glass_08_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.orange_bump_02_pivot.geometry} material={materials.orange_bump} />
      <mesh geometry={nodes.chrome_08_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.o_glass_07_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.o_glass_06_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.silver_03_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.silver_02_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.black_shiny_07_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.glass_06_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.chrome_07_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_06_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_shiny_06_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_shiny_05_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.glass_05_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_04_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.orange_bump_01_pivot.geometry} material={materials.orange_bump} />
      <mesh geometry={nodes.o_glass_05_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.chrome_04_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.chrome_03_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.lights_01_pivot.geometry} material={materials.lights} />
      <mesh geometry={nodes.black_shiny_04_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.glass_03_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_02_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.glass_01_pivot.geometry} material={materials.glass} />
      <mesh geometry={nodes.black_matt_28_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.chrome_09_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_27_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_26_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_25_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_shiny_02_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_matt_24_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_23_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_22_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_21_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.chrome_02_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.black_matt_20_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.o_glass_04_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.black_matt_19_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.chrome_01_pivot.geometry} material={materials.chrome} />
      <mesh geometry={nodes.o_glass_03_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.black_matt_18_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_17_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.o_glass_02_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.o_glass_b_02_pivot.geometry} material={materials.o_glass_b} />
      <mesh geometry={nodes.o_glass_01_pivot.geometry} material={materials.o_glass} />
      <mesh geometry={nodes.d_glass_01_pivot.geometry} material={materials.d_glass} />
      <mesh geometry={nodes.black_matt_16_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_15_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.tire_04_pivot.geometry} material={materials.tire} />
      <mesh geometry={nodes.r_glass_01_pivot.geometry} material={materials.r_glass} />
      <mesh geometry={nodes.black_matt_10_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_11_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_12_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_13_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.tire_01_pivot.geometry} material={materials.tire} />
      <mesh geometry={nodes.black_matt_02_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_03_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.silver_01_pivot.geometry} material={materials.silver} />
      <mesh geometry={nodes.black_matt_04_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_05_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_06_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_07_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_shiny_01_pivot.geometry} material={materials.black_shiny} />
      <mesh geometry={nodes.black_matt_08_pivot.geometry} material={materials.black_matt} />
      <mesh geometry={nodes.black_matt_09_pivot.geometry} material={materials.black_matt} />
      </group>
  )
}


